/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A grammar compiled against a tokenizer, ready to drive a matcher. */
export declare class CompiledGrammar {
  /** The underlying grammar. */
  grammar(): Grammar
  /** The tokenizer info the grammar was compiled against. */
  tokenizerInfo(): TokenizerInfo
  /** Approximate in-memory size of the compiled grammar, in bytes. */
  memorySizeBytes(): bigint
  /** Serializes the compiled grammar without embedding the full tokenizer info. */
  serializeJson(): string
  static deserialize_json(jsonString: string, tokenizerInfo: TokenizerInfo): CompiledGrammar
}

/** A context-free grammar compiled from EBNF, JSON Schema, regex, or a structural tag. */
export declare class Grammar {
  /** Serializes the grammar to its `"v14"` JSON form. */
  serializeJson(): string
  /** The EBNF (GBNF) string form of the grammar. */
  toString(): string
  static from_ebnf(ebnfString: string, rootRuleName: string): Grammar
  static from_json_schema(schema: string, anyWhitespace: boolean, indent: number | undefined | null, separatorItem: string | undefined | null, separatorKv: string | undefined | null, strictMode: boolean, maxWhitespaceCnt: number | undefined | null, printConvertedEbnf: boolean, anyOrder: boolean): Grammar
  static from_regex(regexString: string, printConvertedEbnf: boolean): Grammar
  static from_structural_tag(structuralTagJson: string): Grammar
  static builtin_json_grammar(): Grammar
  static union(grammars: Array<string>): Grammar
  static concat(grammars: Array<string>): Grammar
  static deserialize_json(jsonString: string): Grammar
}

/** Compiles grammars against a tokenizer, with a result cache. */
export declare class GrammarCompiler {
  /** Compiles an existing [`Grammar`]. */
  compileGrammarEbnf(grammar: Grammar): CompiledGrammar
  /** Compiles a grammar from an EBNF string. */
  compileGrammarFromStrings(ebnfString: string, rootRuleName: string): CompiledGrammar
  /** Compiles a JSON Schema string. */
  compileJsonSchema(schema: string, anyWhitespace: boolean, indent: number | undefined | null, separatorItem: string | undefined | null, separatorKv: string | undefined | null, strictMode: boolean, maxWhitespaceCnt: number | undefined | null, anyOrder: boolean): CompiledGrammar
  /** Compiles a regular expression. */
  compileRegex(regex: string): CompiledGrammar
  /** Compiles a structural-tag JSON document. */
  compileStructuralTag(structuralTagJson: string): CompiledGrammar
  /** Compiles the built-in JSON grammar. */
  compileBuiltinJsonGrammar(): CompiledGrammar
  /** Clears the result cache. */
  clearCache(): void
  /** The current cache memory usage, in bytes. */
  getCacheSizeBytes(): number
  /** The cache memory limit, in bytes. */
  cacheLimitBytes(): number
  constructor(tokenizerInfo: TokenizerInfo, maxThreads: number, cacheEnabled: boolean, cacheLimitBytes: number)
}

/** Drives constrained decoding over a compiled grammar. */
export declare class GrammarMatcher {
  /** Accepts a single token id, advancing the matcher. Returns whether it was accepted. */
  acceptToken(tokenId: number, debugPrint: boolean): boolean
  /** Accepts a UTF-8 string, advancing the matcher. Returns whether it was accepted. */
  acceptString(input: string, debugPrint: boolean): boolean
  /** Whether the matcher has reached an accepting terminal state. */
  isTerminated(): boolean
  /** Whether the grammar is fully matched (root completed). */
  isCompleted(): boolean
  /** Resets the matcher to its initial state. */
  reset(): void
  /** Rolls back the last `num_tokens` accepted tokens. */
  rollback(numTokens: number): void
  /** Returns a deep copy of the matcher at its current state. */
  fork(): GrammarMatcher
  /** The stop token ids the matcher accepts as terminators. */
  stopTokenIds(): Array<number>
  constructor(compiledGrammar: CompiledGrammar, overrideStopTokens: Array<number> | undefined | null, terminateWithoutStopToken: boolean, maxRollbackTokens: number)
}

/** A thin opaque wrapper over [`xgrammar::tokenizer::TokenizerInfo`]. */
export declare class TokenizerInfo {
  /** The vocabulary type, as the integer `VocabType` value. */
  vocabType(): number
  /** The vocabulary size (including padding tokens). */
  vocabSize(): number
  /** Whether a prefix space is added during tokenization. */
  addPrefixSpace(): boolean
  /**
   * The decoded byte string of each token id.
   *
   * Omitted on the wasm backend, which cannot return `Vec<Vec<u8>>` directly; the Python
   * tests only exercise this under PyO3.
   */
  decodedVocab(): Array<Array<number>>
  /** The stop token ids. */
  stopTokenIds(): Array<number>
  /** The special token ids. */
  specialTokenIds(): Array<number>
  /** Serializes the tokenizer info to its `"v14"` JSON form. */
  serializeJson(): string
  /** Dumps tokenizer metadata (vocab type and prefix-space flag) as JSON. */
  dumpMetadata(): string
  constructor(encodedVocab: Array<string>, vocabType: number, vocabSize: number | undefined | null, stopTokenIds: Array<number> | undefined | null, addPrefixSpace: boolean)
  static from_vocab_and_metadata(encodedVocab: Array<string>, metadata: string): TokenizerInfo
  static deserialize_json(jsonString: string): TokenizerInfo
  static _detect_metadata_from_hf(backendStr: string): string
}

/**
 * How a tokenizer vocabulary is encoded (RAW, BYTE_FALLBACK, BYTE_LEVEL).
 *
 * No explicit discriminants — NAPI's string-enum codegen rejects them. The numeric
 * mapping (0/1/2) lives in [`VocabType::to_core`] / [`VocabType::from_core`] and the
 * `TryFrom<i32>` impl, which the Python layer relies on.
 */
export declare const enum VocabType {
  /** Tokens are used verbatim. */
  Raw = 'Raw',
  /** SentencePiece-style byte fallback encoding. */
  ByteFallback = 'ByteFallback',
  /** GPT-2-style byte-level encoding. */
  ByteLevel = 'ByteLevel'
}

/**
 * A backend-agnostic error wrapping a message — exported so NAPI / UniFFI / wasm get a
 * native error type. (Unused under the PyO3 backend, which uses [`pyo3::PyErr`] directly.)
 */
export type XgrammarError =
  | { type: 'Invalid', /** The underlying error message. */
message: string }
