// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(xgrammar_rsFFI)
    import xgrammar_rsFFI
#endif

extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    fileprivate init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    fileprivate static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    fileprivate static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall {
            ffi_xgrammar_rs_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0)
        }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    fileprivate func deallocate() {
        try! rustCall { ffi_xgrammar_rs_rustbuffer_free(self, $0) }
    }
}

extension ForeignBytes {
    fileprivate init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

extension Data {
    fileprivate init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws
    -> T
{
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range) })
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws
    -> [UInt8]
{
    let range = reader.offset..<(reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S)
where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow:
            return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case .rustPanic(let message): return message
        }
    }
}

extension NSLock {
    fileprivate func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

extension RustCallStatus {
    fileprivate init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureXgrammarRsInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles.
// These ensure that SWIFT handles always have the lowest bit set
private let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
private let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

private final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterBool: FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}

/// A grammar compiled against a tokenizer, ready to drive a matcher.
public protocol CompiledGrammarProtocol: AnyObject, Sendable {

    /**
     * The underlying grammar.
     */
    func grammar() -> Grammar

    /**
     * Approximate in-memory size of the compiled grammar, in bytes.
     */
    func memorySizeBytes() -> UInt64

    /**
     * Serializes the compiled grammar without embedding the full tokenizer info.
     */
    func serializeJson() -> String

    /**
     * The tokenizer info the grammar was compiled against.
     */
    func tokenizerInfo() -> TokenizerInfo

}
/// A grammar compiled against a tokenizer, ready to drive a matcher.
open class CompiledGrammar: CompiledGrammarProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_xgrammar_rs_fn_clone_compiledgrammar(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_xgrammar_rs_fn_free_compiledgrammar(handle, $0) }
    }

    /**
     * The underlying grammar.
     */
    open func grammar() -> Grammar {
        return try! FfiConverterTypeGrammar_lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_compiledgrammar_grammar(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

    /**
     * Approximate in-memory size of the compiled grammar, in bytes.
     */
    open func memorySizeBytes() -> UInt64 {
        return try! FfiConverterUInt64.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_compiledgrammar_memory_size_bytes(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

    /**
     * Serializes the compiled grammar without embedding the full tokenizer info.
     */
    open func serializeJson() -> String {
        return try! FfiConverterString.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_compiledgrammar_serialize_json(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

    /**
     * The tokenizer info the grammar was compiled against.
     */
    open func tokenizerInfo() -> TokenizerInfo {
        return try! FfiConverterTypeTokenizerInfo_lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_compiledgrammar_tokenizer_info(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompiledGrammar: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = CompiledGrammar

    public static func lift(_ handle: UInt64) throws -> CompiledGrammar {
        return CompiledGrammar(unsafeFromHandle: handle)
    }

    public static func lower(_ value: CompiledGrammar) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
        -> CompiledGrammar
    {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: CompiledGrammar, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeCompiledGrammar_lift(_ handle: UInt64) throws -> CompiledGrammar {
    return try FfiConverterTypeCompiledGrammar.lift(handle)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeCompiledGrammar_lower(_ value: CompiledGrammar) -> UInt64 {
    return FfiConverterTypeCompiledGrammar.lower(value)
}

/// A context-free grammar compiled from EBNF, JSON Schema, regex, or a structural tag.
public protocol GrammarProtocol: AnyObject, Sendable {

    /**
     * Serializes the grammar to its `"v14"` JSON form.
     */
    func serializeJson() -> String

    /**
     * The EBNF (GBNF) string form of the grammar.
     */
    func toString() -> String

}
/// A context-free grammar compiled from EBNF, JSON Schema, regex, or a structural tag.
open class Grammar: GrammarProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_xgrammar_rs_fn_clone_grammar(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_xgrammar_rs_fn_free_grammar(handle, $0) }
    }

    /**
     * Serializes the grammar to its `"v14"` JSON form.
     */
    open func serializeJson() -> String {
        return try! FfiConverterString.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_grammar_serialize_json(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

    /**
     * The EBNF (GBNF) string form of the grammar.
     */
    open func toString() -> String {
        return try! FfiConverterString.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_grammar_to_string(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeGrammar: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Grammar

    public static func lift(_ handle: UInt64) throws -> Grammar {
        return Grammar(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Grammar) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Grammar {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Grammar, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeGrammar_lift(_ handle: UInt64) throws -> Grammar {
    return try FfiConverterTypeGrammar.lift(handle)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeGrammar_lower(_ value: Grammar) -> UInt64 {
    return FfiConverterTypeGrammar.lower(value)
}

/// Compiles grammars against a tokenizer, with a result cache.
public protocol GrammarCompilerProtocol: AnyObject, Sendable {

    /**
     * The cache memory limit, in bytes.
     */
    func cacheLimitBytes() -> Int64

    /**
     * Clears the result cache.
     */
    func clearCache()

    /**
     * Compiles the built-in JSON grammar.
     */
    func compileBuiltinJsonGrammar() -> CompiledGrammar

    /**
     * Compiles an existing [`Grammar`].
     */
    func compileGrammarEbnf(grammar: Grammar) -> CompiledGrammar

    /**
     * Compiles a grammar from an EBNF string.
     */
    func compileGrammarFromStrings(ebnfString: String, rootRuleName: String) -> CompiledGrammar

    /**
     * Compiles a JSON Schema string.
     */
    func compileJsonSchema(
        schema: String, anyWhitespace: Bool, indent: Int32?, separatorItem: String?,
        separatorKv: String?, strictMode: Bool, maxWhitespaceCnt: Int32?, anyOrder: Bool
    ) -> CompiledGrammar

    /**
     * Compiles a regular expression.
     */
    func compileRegex(regex: String) -> CompiledGrammar

    /**
     * Compiles a structural-tag JSON document.
     */
    func compileStructuralTag(structuralTagJson: String) throws -> CompiledGrammar

    /**
     * The current cache memory usage, in bytes.
     */
    func getCacheSizeBytes() -> Int64

}
/// Compiles grammars against a tokenizer, with a result cache.
open class GrammarCompiler: GrammarCompilerProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_xgrammar_rs_fn_clone_grammarcompiler(self.handle, $0) }
    }
    public convenience init(
        tokenizerInfo: TokenizerInfo, maxThreads: Int32, cacheEnabled: Bool, cacheLimitBytes: Int64
    ) {
        let handle =
            try! rustCall {
                uniffi_xgrammar_rs_fn_constructor_grammarcompiler_new(
                    FfiConverterTypeTokenizerInfo_lower(tokenizerInfo),
                    FfiConverterInt32.lower(maxThreads),
                    FfiConverterBool.lower(cacheEnabled),
                    FfiConverterInt64.lower(cacheLimitBytes), $0
                )
            }
        self.init(unsafeFromHandle: handle)
    }

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_xgrammar_rs_fn_free_grammarcompiler(handle, $0) }
    }

    /**
     * The cache memory limit, in bytes.
     */
    open func cacheLimitBytes() -> Int64 {
        return try! FfiConverterInt64.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_grammarcompiler_cache_limit_bytes(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

    /**
     * Clears the result cache.
     */
    open func clearCache() {
        try! rustCall {
            uniffi_xgrammar_rs_fn_method_grammarcompiler_clear_cache(
                self.uniffiCloneHandle(), $0
            )
        }
    }

    /**
     * Compiles the built-in JSON grammar.
     */
    open func compileBuiltinJsonGrammar() -> CompiledGrammar {
        return try! FfiConverterTypeCompiledGrammar_lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_grammarcompiler_compile_builtin_json_grammar(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

    /**
     * Compiles an existing [`Grammar`].
     */
    open func compileGrammarEbnf(grammar: Grammar) -> CompiledGrammar {
        return try! FfiConverterTypeCompiledGrammar_lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_grammarcompiler_compile_grammar_ebnf(
                    self.uniffiCloneHandle(),
                    FfiConverterTypeGrammar_lower(grammar), $0
                )
            })
    }

    /**
     * Compiles a grammar from an EBNF string.
     */
    open func compileGrammarFromStrings(ebnfString: String, rootRuleName: String) -> CompiledGrammar
    {
        return try! FfiConverterTypeCompiledGrammar_lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_grammarcompiler_compile_grammar_from_strings(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(ebnfString),
                    FfiConverterString.lower(rootRuleName), $0
                )
            })
    }

    /**
     * Compiles a JSON Schema string.
     */
    open func compileJsonSchema(
        schema: String, anyWhitespace: Bool, indent: Int32?, separatorItem: String?,
        separatorKv: String?, strictMode: Bool, maxWhitespaceCnt: Int32?, anyOrder: Bool
    ) -> CompiledGrammar {
        return try! FfiConverterTypeCompiledGrammar_lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_grammarcompiler_compile_json_schema(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(schema),
                    FfiConverterBool.lower(anyWhitespace),
                    FfiConverterOptionInt32.lower(indent),
                    FfiConverterOptionString.lower(separatorItem),
                    FfiConverterOptionString.lower(separatorKv),
                    FfiConverterBool.lower(strictMode),
                    FfiConverterOptionInt32.lower(maxWhitespaceCnt),
                    FfiConverterBool.lower(anyOrder), $0
                )
            })
    }

    /**
     * Compiles a regular expression.
     */
    open func compileRegex(regex: String) -> CompiledGrammar {
        return try! FfiConverterTypeCompiledGrammar_lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_grammarcompiler_compile_regex(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(regex), $0
                )
            })
    }

    /**
     * Compiles a structural-tag JSON document.
     */
    open func compileStructuralTag(structuralTagJson: String) throws -> CompiledGrammar {
        return try FfiConverterTypeCompiledGrammar_lift(
            try rustCallWithError(FfiConverterTypeXgrammarError_lift) {
                uniffi_xgrammar_rs_fn_method_grammarcompiler_compile_structural_tag(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(structuralTagJson), $0
                )
            })
    }

    /**
     * The current cache memory usage, in bytes.
     */
    open func getCacheSizeBytes() -> Int64 {
        return try! FfiConverterInt64.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_grammarcompiler_get_cache_size_bytes(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeGrammarCompiler: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = GrammarCompiler

    public static func lift(_ handle: UInt64) throws -> GrammarCompiler {
        return GrammarCompiler(unsafeFromHandle: handle)
    }

    public static func lower(_ value: GrammarCompiler) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
        -> GrammarCompiler
    {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: GrammarCompiler, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeGrammarCompiler_lift(_ handle: UInt64) throws -> GrammarCompiler {
    return try FfiConverterTypeGrammarCompiler.lift(handle)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeGrammarCompiler_lower(_ value: GrammarCompiler) -> UInt64 {
    return FfiConverterTypeGrammarCompiler.lower(value)
}

/// Drives constrained decoding over a compiled grammar.
public protocol GrammarMatcherProtocol: AnyObject, Sendable {

    /**
     * Accepts a UTF-8 string, advancing the matcher. Returns whether it was accepted.
     */
    func acceptString(input: String, debugPrint: Bool) -> Bool

    /**
     * Accepts a single token id, advancing the matcher. Returns whether it was accepted.
     */
    func acceptToken(tokenId: Int32, debugPrint: Bool) -> Bool

    /**
     * Returns a deep copy of the matcher at its current state.
     */
    func fork() -> GrammarMatcher

    /**
     * Whether the grammar is fully matched (root completed).
     */
    func isCompleted() -> Bool

    /**
     * Whether the matcher has reached an accepting terminal state.
     */
    func isTerminated() -> Bool

    /**
     * Resets the matcher to its initial state.
     */
    func reset()

    /**
     * Rolls back the last `num_tokens` accepted tokens.
     */
    func rollback(numTokens: Int32)

    /**
     * The stop token ids the matcher accepts as terminators.
     */
    func stopTokenIds() -> [Int32]

}
/// Drives constrained decoding over a compiled grammar.
open class GrammarMatcher: GrammarMatcherProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_xgrammar_rs_fn_clone_grammarmatcher(self.handle, $0) }
    }
    public convenience init(
        compiledGrammar: CompiledGrammar, overrideStopTokens: [Int32]?,
        terminateWithoutStopToken: Bool, maxRollbackTokens: Int32
    ) {
        let handle =
            try! rustCall {
                uniffi_xgrammar_rs_fn_constructor_grammarmatcher_new(
                    FfiConverterTypeCompiledGrammar_lower(compiledGrammar),
                    FfiConverterOptionSequenceInt32.lower(overrideStopTokens),
                    FfiConverterBool.lower(terminateWithoutStopToken),
                    FfiConverterInt32.lower(maxRollbackTokens), $0
                )
            }
        self.init(unsafeFromHandle: handle)
    }

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_xgrammar_rs_fn_free_grammarmatcher(handle, $0) }
    }

    /**
     * Accepts a UTF-8 string, advancing the matcher. Returns whether it was accepted.
     */
    open func acceptString(input: String, debugPrint: Bool) -> Bool {
        return try! FfiConverterBool.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_grammarmatcher_accept_string(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(input),
                    FfiConverterBool.lower(debugPrint), $0
                )
            })
    }

    /**
     * Accepts a single token id, advancing the matcher. Returns whether it was accepted.
     */
    open func acceptToken(tokenId: Int32, debugPrint: Bool) -> Bool {
        return try! FfiConverterBool.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_grammarmatcher_accept_token(
                    self.uniffiCloneHandle(),
                    FfiConverterInt32.lower(tokenId),
                    FfiConverterBool.lower(debugPrint), $0
                )
            })
    }

    /**
     * Returns a deep copy of the matcher at its current state.
     */
    open func fork() -> GrammarMatcher {
        return try! FfiConverterTypeGrammarMatcher_lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_grammarmatcher_fork(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

    /**
     * Whether the grammar is fully matched (root completed).
     */
    open func isCompleted() -> Bool {
        return try! FfiConverterBool.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_grammarmatcher_is_completed(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

    /**
     * Whether the matcher has reached an accepting terminal state.
     */
    open func isTerminated() -> Bool {
        return try! FfiConverterBool.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_grammarmatcher_is_terminated(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

    /**
     * Resets the matcher to its initial state.
     */
    open func reset() {
        try! rustCall {
            uniffi_xgrammar_rs_fn_method_grammarmatcher_reset(
                self.uniffiCloneHandle(), $0
            )
        }
    }

    /**
     * Rolls back the last `num_tokens` accepted tokens.
     */
    open func rollback(numTokens: Int32) {
        try! rustCall {
            uniffi_xgrammar_rs_fn_method_grammarmatcher_rollback(
                self.uniffiCloneHandle(),
                FfiConverterInt32.lower(numTokens), $0
            )
        }
    }

    /**
     * The stop token ids the matcher accepts as terminators.
     */
    open func stopTokenIds() -> [Int32] {
        return try! FfiConverterSequenceInt32.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_grammarmatcher_stop_token_ids(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeGrammarMatcher: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = GrammarMatcher

    public static func lift(_ handle: UInt64) throws -> GrammarMatcher {
        return GrammarMatcher(unsafeFromHandle: handle)
    }

    public static func lower(_ value: GrammarMatcher) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
        -> GrammarMatcher
    {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: GrammarMatcher, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeGrammarMatcher_lift(_ handle: UInt64) throws -> GrammarMatcher {
    return try FfiConverterTypeGrammarMatcher.lift(handle)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeGrammarMatcher_lower(_ value: GrammarMatcher) -> UInt64 {
    return FfiConverterTypeGrammarMatcher.lower(value)
}

/// A thin opaque wrapper over [`xgrammar::tokenizer::TokenizerInfo`].
public protocol TokenizerInfoProtocol: AnyObject, Sendable {

    /**
     * Whether a prefix space is added during tokenization.
     */
    func addPrefixSpace() -> Bool

    /**
     * The decoded byte string of each token id.
     *
     * Omitted on the wasm backend, which cannot return `Vec<Vec<u8>>` directly; the Python
     * tests only exercise this under PyO3.
     */
    func decodedVocab() -> [Data]

    /**
     * Dumps tokenizer metadata (vocab type and prefix-space flag) as JSON.
     */
    func dumpMetadata() -> String

    /**
     * Serializes the tokenizer info to its `"v14"` JSON form.
     */
    func serializeJson() -> String

    /**
     * The special token ids.
     */
    func specialTokenIds() -> [Int32]

    /**
     * The stop token ids.
     */
    func stopTokenIds() -> [Int32]

    /**
     * The vocabulary size (including padding tokens).
     */
    func vocabSize() -> Int32

    /**
     * The vocabulary type, as the integer `VocabType` value.
     */
    func vocabType() -> Int32

}
/// A thin opaque wrapper over [`xgrammar::tokenizer::TokenizerInfo`].
open class TokenizerInfo: TokenizerInfoProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_xgrammar_rs_fn_clone_tokenizerinfo(self.handle, $0) }
    }
    public convenience init(
        encodedVocab: [String], vocabType: Int32, vocabSize: Int32?, stopTokenIds: [Int32]?,
        addPrefixSpace: Bool
    ) throws {
        let handle =
            try rustCallWithError(FfiConverterTypeXgrammarError_lift) {
                uniffi_xgrammar_rs_fn_constructor_tokenizerinfo_new(
                    FfiConverterSequenceString.lower(encodedVocab),
                    FfiConverterInt32.lower(vocabType),
                    FfiConverterOptionInt32.lower(vocabSize),
                    FfiConverterOptionSequenceInt32.lower(stopTokenIds),
                    FfiConverterBool.lower(addPrefixSpace), $0
                )
            }
        self.init(unsafeFromHandle: handle)
    }

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_xgrammar_rs_fn_free_tokenizerinfo(handle, $0) }
    }

    /**
     * Whether a prefix space is added during tokenization.
     */
    open func addPrefixSpace() -> Bool {
        return try! FfiConverterBool.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_tokenizerinfo_add_prefix_space(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

    /**
     * The decoded byte string of each token id.
     *
     * Omitted on the wasm backend, which cannot return `Vec<Vec<u8>>` directly; the Python
     * tests only exercise this under PyO3.
     */
    open func decodedVocab() -> [Data] {
        return try! FfiConverterSequenceData.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_tokenizerinfo_decoded_vocab(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

    /**
     * Dumps tokenizer metadata (vocab type and prefix-space flag) as JSON.
     */
    open func dumpMetadata() -> String {
        return try! FfiConverterString.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_tokenizerinfo_dump_metadata(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

    /**
     * Serializes the tokenizer info to its `"v14"` JSON form.
     */
    open func serializeJson() -> String {
        return try! FfiConverterString.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_tokenizerinfo_serialize_json(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

    /**
     * The special token ids.
     */
    open func specialTokenIds() -> [Int32] {
        return try! FfiConverterSequenceInt32.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_tokenizerinfo_special_token_ids(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

    /**
     * The stop token ids.
     */
    open func stopTokenIds() -> [Int32] {
        return try! FfiConverterSequenceInt32.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_tokenizerinfo_stop_token_ids(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

    /**
     * The vocabulary size (including padding tokens).
     */
    open func vocabSize() -> Int32 {
        return try! FfiConverterInt32.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_tokenizerinfo_vocab_size(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

    /**
     * The vocabulary type, as the integer `VocabType` value.
     */
    open func vocabType() -> Int32 {
        return try! FfiConverterInt32.lift(
            try! rustCall {
                uniffi_xgrammar_rs_fn_method_tokenizerinfo_vocab_type(
                    self.uniffiCloneHandle(), $0
                )
            })
    }

}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeTokenizerInfo: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = TokenizerInfo

    public static func lift(_ handle: UInt64) throws -> TokenizerInfo {
        return TokenizerInfo(unsafeFromHandle: handle)
    }

    public static func lower(_ value: TokenizerInfo) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
        -> TokenizerInfo
    {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: TokenizerInfo, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTokenizerInfo_lift(_ handle: UInt64) throws -> TokenizerInfo {
    return try FfiConverterTypeTokenizerInfo.lift(handle)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTokenizerInfo_lower(_ value: TokenizerInfo) -> UInt64 {
    return FfiConverterTypeTokenizerInfo.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * How a tokenizer vocabulary is encoded (RAW, BYTE_FALLBACK, BYTE_LEVEL).
 *
 * No explicit discriminants — NAPI's string-enum codegen rejects them. The numeric
 * mapping (0/1/2) lives in [`VocabType::to_core`] / [`VocabType::from_core`] and the
 * `TryFrom<i32>` impl, which the Python layer relies on.
 */

public enum VocabType: Equatable, Hashable {

    /**
     * Tokens are used verbatim.
     */
    case raw
    /**
     * SentencePiece-style byte fallback encoding.
     */
    case byteFallback
    /**
     * GPT-2-style byte-level encoding.
     */
    case byteLevel

}

#if compiler(>=6)
    extension VocabType: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeVocabType: FfiConverterRustBuffer {
    typealias SwiftType = VocabType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VocabType {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .raw

        case 2: return .byteFallback

        case 3: return .byteLevel

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: VocabType, into buf: inout [UInt8]) {
        switch value {

        case .raw:
            writeInt(&buf, Int32(1))

        case .byteFallback:
            writeInt(&buf, Int32(2))

        case .byteLevel:
            writeInt(&buf, Int32(3))

        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeVocabType_lift(_ buf: RustBuffer) throws -> VocabType {
    return try FfiConverterTypeVocabType.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeVocabType_lower(_ value: VocabType) -> RustBuffer {
    return FfiConverterTypeVocabType.lower(value)
}

/// A backend-agnostic error wrapping a message — exported so NAPI / UniFFI / wasm get a
/// native error type. (Unused under the PyO3 backend, which uses [`pyo3::PyErr`] directly.)
public enum XgrammarError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    /**
     * A grammar / schema / serialization operation failed.
     */
    case Invalid(
        /**
         * The underlying error message.
         */
        message: String
    )

    public var errorDescription: String? {
        String(reflecting: self)
    }

}

#if compiler(>=6)
    extension XgrammarError: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeXgrammarError: FfiConverterRustBuffer {
    typealias SwiftType = XgrammarError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws
        -> XgrammarError
    {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1:
            return .Invalid(
                message: try FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: XgrammarError, into buf: inout [UInt8]) {
        switch value {

        case .Invalid(let message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)

        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeXgrammarError_lift(_ buf: RustBuffer) throws -> XgrammarError {
    return try FfiConverterTypeXgrammarError.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeXgrammarError_lower(_ value: XgrammarError) -> RustBuffer {
    return FfiConverterTypeXgrammarError.lower(value)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionInt32: FfiConverterRustBuffer {
    typealias SwiftType = Int32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionSequenceInt32: FfiConverterRustBuffer {
    typealias SwiftType = [Int32]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceInt32: FfiConverterRustBuffer {
    typealias SwiftType = [Int32]

    public static func write(_ value: [Int32], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterInt32.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Int32] {
        let len: Int32 = try readInt(&buf)
        var seq = [Int32]()
        seq.reserveCapacity(Int(len))
        for _ in 0..<len {
            seq.append(try FfiConverterInt32.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0..<len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceData: FfiConverterRustBuffer {
    typealias SwiftType = [Data]

    public static func write(_ value: [Data], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterData.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Data] {
        let len: Int32 = try readInt(&buf)
        var seq = [Data]()
        seq.reserveCapacity(Int(len))
        for _ in 0..<len {
            seq.append(try FfiConverterData.read(from: &buf))
        }
        return seq
    }
}
public func compiledGrammarDeserializeJson(jsonString: String, tokenizerInfo: TokenizerInfo) throws
    -> CompiledGrammar
{
    return try FfiConverterTypeCompiledGrammar_lift(
        try rustCallWithError(FfiConverterTypeXgrammarError_lift) {
            uniffi_xgrammar_rs_fn_func_compiled_grammar_deserialize_json(
                FfiConverterString.lower(jsonString),
                FfiConverterTypeTokenizerInfo_lower(tokenizerInfo), $0
            )
        })
}
public func grammarBuiltinJsonGrammar() -> Grammar {
    return try! FfiConverterTypeGrammar_lift(
        try! rustCall {
            uniffi_xgrammar_rs_fn_func_grammar_builtin_json_grammar(
                $0
            )
        })
}
public func grammarConcat(grammars: [String]) throws -> Grammar {
    return try FfiConverterTypeGrammar_lift(
        try rustCallWithError(FfiConverterTypeXgrammarError_lift) {
            uniffi_xgrammar_rs_fn_func_grammar_concat(
                FfiConverterSequenceString.lower(grammars), $0
            )
        })
}
public func grammarDeserializeJson(jsonString: String) throws -> Grammar {
    return try FfiConverterTypeGrammar_lift(
        try rustCallWithError(FfiConverterTypeXgrammarError_lift) {
            uniffi_xgrammar_rs_fn_func_grammar_deserialize_json(
                FfiConverterString.lower(jsonString), $0
            )
        })
}
public func grammarFromEbnf(ebnfString: String, rootRuleName: String) throws -> Grammar {
    return try FfiConverterTypeGrammar_lift(
        try rustCallWithError(FfiConverterTypeXgrammarError_lift) {
            uniffi_xgrammar_rs_fn_func_grammar_from_ebnf(
                FfiConverterString.lower(ebnfString),
                FfiConverterString.lower(rootRuleName), $0
            )
        })
}
public func grammarFromJsonSchema(
    schema: String, anyWhitespace: Bool, indent: Int32?, separatorItem: String?,
    separatorKv: String?, strictMode: Bool, maxWhitespaceCnt: Int32?, printConvertedEbnf: Bool,
    anyOrder: Bool
) throws -> Grammar {
    return try FfiConverterTypeGrammar_lift(
        try rustCallWithError(FfiConverterTypeXgrammarError_lift) {
            uniffi_xgrammar_rs_fn_func_grammar_from_json_schema(
                FfiConverterString.lower(schema),
                FfiConverterBool.lower(anyWhitespace),
                FfiConverterOptionInt32.lower(indent),
                FfiConverterOptionString.lower(separatorItem),
                FfiConverterOptionString.lower(separatorKv),
                FfiConverterBool.lower(strictMode),
                FfiConverterOptionInt32.lower(maxWhitespaceCnt),
                FfiConverterBool.lower(printConvertedEbnf),
                FfiConverterBool.lower(anyOrder), $0
            )
        })
}
public func grammarFromRegex(regexString: String, printConvertedEbnf: Bool) throws -> Grammar {
    return try FfiConverterTypeGrammar_lift(
        try rustCallWithError(FfiConverterTypeXgrammarError_lift) {
            uniffi_xgrammar_rs_fn_func_grammar_from_regex(
                FfiConverterString.lower(regexString),
                FfiConverterBool.lower(printConvertedEbnf), $0
            )
        })
}
public func grammarFromStructuralTag(structuralTagJson: String) throws -> Grammar {
    return try FfiConverterTypeGrammar_lift(
        try rustCallWithError(FfiConverterTypeXgrammarError_lift) {
            uniffi_xgrammar_rs_fn_func_grammar_from_structural_tag(
                FfiConverterString.lower(structuralTagJson), $0
            )
        })
}
public func grammarUnion(grammars: [String]) throws -> Grammar {
    return try FfiConverterTypeGrammar_lift(
        try rustCallWithError(FfiConverterTypeXgrammarError_lift) {
            uniffi_xgrammar_rs_fn_func_grammar_union(
                FfiConverterSequenceString.lower(grammars), $0
            )
        })
}
public func tokenizerInfoDetectMetadataFromHf(backendStr: String) throws -> String {
    return try FfiConverterString.lift(
        try rustCallWithError(FfiConverterTypeXgrammarError_lift) {
            uniffi_xgrammar_rs_fn_func_tokenizer_info__detect_metadata_from_hf(
                FfiConverterString.lower(backendStr), $0
            )
        })
}
public func tokenizerInfoDeserializeJson(jsonString: String) throws -> TokenizerInfo {
    return try FfiConverterTypeTokenizerInfo_lift(
        try rustCallWithError(FfiConverterTypeXgrammarError_lift) {
            uniffi_xgrammar_rs_fn_func_tokenizer_info_deserialize_json(
                FfiConverterString.lower(jsonString), $0
            )
        })
}
public func tokenizerInfoFromVocabAndMetadata(encodedVocab: [String], metadata: String) throws
    -> TokenizerInfo
{
    return try FfiConverterTypeTokenizerInfo_lift(
        try rustCallWithError(FfiConverterTypeXgrammarError_lift) {
            uniffi_xgrammar_rs_fn_func_tokenizer_info_from_vocab_and_metadata(
                FfiConverterSequenceString.lower(encodedVocab),
                FfiConverterString.lower(metadata), $0
            )
        })
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_xgrammar_rs_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_xgrammar_rs_checksum_func_compiled_grammar_deserialize_json() != 24099 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_func_grammar_builtin_json_grammar() != 8945 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_func_grammar_concat() != 5519 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_func_grammar_deserialize_json() != 60886 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_func_grammar_from_ebnf() != 5744 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_func_grammar_from_json_schema() != 11142 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_func_grammar_from_regex() != 30139 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_func_grammar_from_structural_tag() != 22672 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_func_grammar_union() != 26047 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_func_tokenizer_info__detect_metadata_from_hf() != 49208 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_func_tokenizer_info_deserialize_json() != 44800 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_func_tokenizer_info_from_vocab_and_metadata() != 40111 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_compiledgrammar_grammar() != 43562 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_compiledgrammar_memory_size_bytes() != 47290 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_compiledgrammar_serialize_json() != 34432 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_compiledgrammar_tokenizer_info() != 901 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammarcompiler_cache_limit_bytes() != 44569 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammarcompiler_clear_cache() != 6194 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammarcompiler_compile_builtin_json_grammar() != 55798 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammarcompiler_compile_grammar_ebnf() != 40219 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammarcompiler_compile_grammar_from_strings() != 59367 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammarcompiler_compile_json_schema() != 53909 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammarcompiler_compile_regex() != 40922 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammarcompiler_compile_structural_tag() != 2173 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammarcompiler_get_cache_size_bytes() != 950 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammar_serialize_json() != 42309 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammar_to_string() != 5604 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammarmatcher_accept_string() != 40620 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammarmatcher_accept_token() != 45185 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammarmatcher_fork() != 24213 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammarmatcher_is_completed() != 27310 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammarmatcher_is_terminated() != 11311 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammarmatcher_reset() != 12638 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammarmatcher_rollback() != 44035 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_grammarmatcher_stop_token_ids() != 15172 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_tokenizerinfo_add_prefix_space() != 31876 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_tokenizerinfo_decoded_vocab() != 3468 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_tokenizerinfo_dump_metadata() != 19705 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_tokenizerinfo_serialize_json() != 60728 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_tokenizerinfo_special_token_ids() != 12090 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_tokenizerinfo_stop_token_ids() != 51068 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_tokenizerinfo_vocab_size() != 15343 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_method_tokenizerinfo_vocab_type() != 8015 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_constructor_grammarcompiler_new() != 22434 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_constructor_grammarmatcher_new() != 41324 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_xgrammar_rs_checksum_constructor_tokenizerinfo_new() != 12687 {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureXgrammarRsInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
