#!/usr/bin/env bash
set -euo pipefail

# Regenerates xgrammar-pins.toml to match an upstream XGrammar ref and its submodules.
# Usage: scripts/update_pins.sh [ref]
# - ref: git tag/branch/commit to pin (default: v<Cargo.toml version> or $XGRAMMAR_GIT_REF)

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PINS_FILE="${ROOT_DIR}/xgrammar-pins.toml"

URL="${XGRAMMAR_GIT_URL:-https://github.com/mlc-ai/xgrammar.git}"
PKG_VERSION="$(sed -n 's/^version = "\(.*\)"/\1/p' "${ROOT_DIR}/Cargo.toml" | head -n 1 || true)"
DEFAULT_REF="v${PKG_VERSION:-0.0.0}"
REF="${1:-${XGRAMMAR_GIT_REF:-${DEFAULT_REF}}}"

if ! command -v git >/dev/null 2>&1; then
  echo "error: git is required" >&2
  exit 1
fi

TMP_DIR="$(mktemp -d)"
cleanup() { rm -rf "${TMP_DIR}"; }
trap cleanup EXIT

echo "Cloning ${URL} @ ${REF}..."
git clone --depth 1 --branch "${REF}" "${URL}" "${TMP_DIR}/xgrammar" >/dev/null

pushd "${TMP_DIR}/xgrammar" >/dev/null
git submodule update --init --recursive --depth 1 >/dev/null

sub_sha() {
  local path="$1"
  git -C "${TMP_DIR}/xgrammar/${path}" rev-parse HEAD
}

sub_url() {
  local path="$1"
  git config --file .gitmodules --get "submodule.${path}.url"
}

CPTRACE_SHA="$(sub_sha 3rdparty/cpptrace)"
DL_PACK_SHA="$(sub_sha 3rdparty/dlpack)"
GTEST_SHA="$(sub_sha 3rdparty/googletest)"

CPTRACE_URL="$(sub_url 3rdparty/cpptrace)"
DL_PACK_URL="$(sub_url 3rdparty/dlpack)"
GTEST_URL="$(sub_url 3rdparty/googletest)"

popd >/dev/null

cat >"${PINS_FILE}" <<EOF
# Pins for XGrammar repo and submodules used by build.rs
# Auto-generated by scripts/update_pins.sh

[repo]
url = "${URL}"
ref = "${REF}"

[submodules.cpptrace]
path = "3rdparty/cpptrace"
url = "${CPTRACE_URL}"
ref = "${CPTRACE_SHA}"

[submodules.dlpack]
path = "3rdparty/dlpack"
url = "${DL_PACK_URL}"
ref = "${DL_PACK_SHA}"

[submodules.googletest]
path = "3rdparty/googletest"
url = "${GTEST_URL}"
ref = "${GTEST_SHA}"
EOF

echo "Updated ${PINS_FILE}"

